### ISSUE TITLE
Correcting typos

### ISSUE THREAD

**Issue by csdp000** [dotnet/docs.ko-kr#138]
모든 "코트"가 각 테스트 내에서 볼 수 있기 때문에 테스트를 읽을

코트 -&gt; 코드

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [단위 테스트 작성에 대한 모범 사례 - .NET Core](https://docs.microsoft.com/ko-kr/dotnet/core/testing/unit-testing-best-practices#feedback)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-core**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
안녕하세요. , @csdp000 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요. @csdp000 님,
댓글을 남겨 주셔서 감사드리며 Microsoft는 docs.microsoft.com의 환경을 개선하기 위해 노력하고 있습니다. 그러나 귀하의 의견을 처리하기 위해서는 추가 정보가 필요합니다. 자세한 정보를 제공하고 댓글에 대해 명확하게 설명해 주실 수 있으신지요?
**전체 문장으로 다시 의견을 적어주시겠습니까?**

감사합니다.
Microsoft DOCS International 팀

**Comment by CeciAc** [comment]
안녕하세요. @csdp000 님,
댓글을 남겨 주셔서 다시 한번 감사합니다.
죄송하지만, 여전히 누락된 정보가 있어 귀하의 의견을 처리할 수 없습니다. 지금은 이 GitHub 문제를 종결하지만, 향후 더 많은 의견을 제출해 주시면 감사하겠습니다.
감사합니다.
Microsoft DOCS International 팀
