### ISSUE TITLE
How to translate advanced feature

### ISSUE THREAD

**Issue by leedors527** [dotnet/docs.ko-kr#180]
I want to translate english documentation to anothor language.
Some document can but some document is not (like https://docs.microsoft.com/ko-kr/dotnet/framework/wpf/advanced/wpf-architecture?view=netframework-4.8)

How can i translate it?

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: c08cf280-bb74-6eab-3475-b42508967afc
* Version Independent ID: 2dfcc4dd-6241-84d6-994a-413a54a259ff
* Content: [WPF 아키텍처](https://docs.microsoft.com/ko-kr/dotnet/framework/wpf/advanced/wpf-architecture?view=netframework-4.8#feedback)
* Content Source: [docs/framework/wpf/advanced/wpf-architecture.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/framework/wpf/advanced/wpf-architecture.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JasonCard** [comment]
Hi @leedors527 

Thank you for your feedback and we appreciate your request to contribute to our translation. 
Unfortunately, we have temporarily disabled Community Contribution (the "Edit" button") for machine translated articles. 
We are currently working on switching to a better Machine Translation engine, and considering ways to improve the process, so we can re-enable this feature in the future. 
In the meantime, we would like to ask for your patience and understanding.

Kind regards,
Microsoft DOCS International Team
cc @CeciAc
