### ISSUE TITLE
번역 제안 Translation suggestion

### ISSUE THREAD

**Issue by KimMan-jae** [dotnet/docs.ko-kr#181]
[여기에 피드백 입력]

In Windows Presentation Foundation (WPF), uniform resource identifiers (URIs) are used to identify and load files in many ways, including the following:

Specifying the user interface (UI) to show when an application first starts.

Loading images.

Navigating to pages.

Loading non-executable data files.

WPF (Windows Presentation Foundation)에서, URI (Uniform Resource Identifier)는 다음과 같은 다양한 상황에서 파일을 식별하고 로드하는 데 사용합니다.

응용 프로그램이 처음 시작될 때 표시 할 UI (사용자 인터페이스) 지정

이미지 로드

페이지 탐색

비실행 데이터 파일 로드

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 469a9e29-6729-8653-9e41-9d5620ab7adf
* Version Independent ID: 2452b6ed-0dd2-df60-80f5-70e7ccdf7abb
* Content: [WPF의 Pack URI](https://docs.microsoft.com/ko-kr/dotnet/framework/wpf/app-development/pack-uris-in-wpf)
* Content Source: [docs/framework/wpf/app-development/pack-uris-in-wpf.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/framework/wpf/app-development/pack-uris-in-wpf.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
안녕하세요. , @KimMan-jae 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요, @KimMan-jae  님. 
피드백을 주셔서 감사합니다. 문제의 페이지가 기계 번역되어 항상 완벽하게 이해할 수 있는 것은 아닙니다. 최근에 오른쪽에 "영어로 읽기" 옵션이 추가되어 언어 설정을 변경하지 않고도 영어 버전으로 전환할 수 있습니다. 
감사합니다.
Microsoft DOCS 국제 팀
