### ISSUE TITLE
오타

### ISSUE THREAD

**Issue by gwangsoo** [dotnet/docs.ko-kr#185]
2번째 줄의 Dockeer -&gt; Docker

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 9fdabc1c-b62f-80c2-a75d-a0f796bc467d
* Version Independent ID: 144abd90-dc22-bf47-b913-d41d473d515e
* Content: [일반 지침](https://docs.microsoft.com/ko-kr/dotnet/standard/microservices-architecture/net-core-net-framework-containers/general-guidance#feedback)
* Content Source: [docs/standard/microservices-architecture/net-core-net-framework-containers/general-guidance.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/standard/microservices-architecture/net-core-net-framework-containers/general-guidance.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by CeciAc** [comment]
안녕하세요. , @gwangsoo 
피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 
감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요, @gwangsoo 님.  
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/dotnet/standard/microservices-architecture/net-core-net-framework-containers/general-guidance#feedback 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
