### ISSUE TITLE
can i use storeName "WebHosting" ? why error? "WebHosting" is not support?

### ISSUE THREAD

**Issue by HaeDalSan** [dotnet/docs.ko-kr#201]
&lt;clientCertificate findValue="contoso.com"  
                               storeLocation="CurrentUser"  
                               storeName="WebHosting"  
                               x509FindType="FindBySubjectName" /&gt;

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 926e4787-e1a8-23ea-4ec1-29a969f0a0b9
* Version Independent ID: 40745b7b-5b60-b66c-0630-4223a7061124
* Content: [인증서 인증을 사용하는 전송 보안](https://docs.microsoft.com/ko-kr/dotnet/framework/wcf/feature-details/transport-security-with-certificate-authentication#feedback)
* Content Source: [docs/framework/wcf/feature-details/transport-security-with-certificate-authentication.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/framework/wcf/feature-details/transport-security-with-certificate-authentication.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wcf**
* GitHub Login: @HongGit
* Microsoft Alias: **wcfsrvt**

**Comment by srvbpigh** [comment]
Hello, @HaeDalSan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @HaeDalSan

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
