### ISSUE TITLE
공용 언어 런타임의 어셈블리의 첫 번째 문장 수정 요청

### ISSUE THREAD

**Issue by azuremaroo** [dotnet/docs.ko-kr#206]
ko-kr 문서의 내용 &gt;&gt;
어셈블리는 형식 구현을 인식하는 데 필요한 정보와 함께 공용 언어 런타임을 제공합니다. 런타임에 대해, 형식은 어셈블리 컨텍스트 외부에 존재하지 않습니다.

en-us 버전 문서 동일 내용 &gt;&gt; 
Assemblies provide the common language runtime with the information it needs to be aware of type implementations. To the runtime, a type does not exist outside the context of an assembly.

수정 예시 &gt;&gt;
어셈블리는 공용 언어 런타임에게 형식 구현에 필요한 정보를 제공합니다. 런타임에 형식은 어셈블리 컨텍스트 외부에 존재하지는 않습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 8ac305e0-d5f4-028e-d801-615e457c9c26
* Version Independent ID: 9abcd631-8133-0e05-b1b4-e22b5319ad1f
* Content: [.NET 어셈블리](https://docs.microsoft.com/ko-kr/dotnet/standard/assembly/#assemblies-in-the-common-language-runtime)
* Content Source: [docs/standard/assembly/index.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/standard/assembly/index.md)
* Product: **dotnet**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @azuremaroo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @azuremaroo 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ko-kr/dotnet/standard/assembly/#assemblies-in-the-common-language-runtime

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
