### ISSUE TITLE
한국어 번역 오류 건의

### ISSUE THREAD

**Issue by cafelattte** [dotnet/docs.ko-kr#208]
영어로는
C# also supports multi-dimensional arrays
라고 적혀있는데 한국어로 번역된 글을 읽을 때에는
C#에서는 다차원 배열s을 지원하지 않습니다
라고 적혀있습니다.

감사합니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 64f269de-137f-a763-a4e2-f2f5b1ce9dd3
* Version Independent ID: ad83c8b9-a95a-e336-ff31-52fb1fdb4b14
* Content: [C# 배열 - C# 언어 둘러보기](https://docs.microsoft.com/ko-kr/dotnet/csharp/tour-of-csharp/arrays#feedback)
* Content Source: [docs/csharp/tour-of-csharp/arrays.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/csharp/tour-of-csharp/arrays.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @cafelattte
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요, @cafelattte 님.
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/dotnet/csharp/tour-of-csharp/arrays#feedback에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
