### ISSUE TITLE
오타 발견

### ISSUE THREAD

**Issue by Kevin-Seo** [dotnet/docs.ko-kr#209]
C# 프로그램은 CLR(공용 언어 런타임)이라고 하는 가상 실행 시스템과 통합된 클래스 라이브러리 세트를 포함하는 Windows의 통합 구성 요소인 .NET Framewor에서 실행됩니다.

.NET Framewor -&gt; .NET Framework

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 91388e65-01f7-d27c-38d0-4e2113cef43a
* Version Independent ID: ad74fdd5-880a-df4c-731c-235c8d42d7db
* Content: [C# 언어 및 .NET Framework 소개](https://docs.microsoft.com/ko-kr/dotnet/csharp/getting-started/introduction-to-the-csharp-language-and-the-net-framework#feedback)
* Content Source: [docs/csharp/getting-started/introduction-to-the-csharp-language-and-the-net-framework.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/csharp/getting-started/introduction-to-the-csharp-language-and-the-net-framework.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Kevin-Seo** [comment]
https://github.com/dotnet/docs.ko-kr/commit/ef911594dcd63b8b763767eb04be6d5bd3738905

**Comment by srvbpigh** [comment]
Hello, @Kevin-Seo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
안녕하세요, @Kevin-Seo님.   

피드백을 주셔서 감사합니다.  

당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/dotnet/csharp/getting-started/introduction-to-the-csharp-language-and-the-net-framework#feedback에 게시했습니다.   

당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다.  

감사합니다.  
Microsoft DOCS 국제 팀
