### ISSUE TITLE
"C# 언어 사양"과 "스택 할당"의 링크가 반대입니다

### ISSUE THREAD

**Issue by sopepos** [dotnet/docs.ko-kr#221]
이 페이지 가장 마지막 문장,  "자세한 내용은 'C# 언어 사양'의 '스택 할당' 섹션과 중첩 컨텍스트기능 제안 노트의 stackalloc허용을 참조하세요." 에서,
"C# 언어 사양"의 링크와 "스택 할당" 링크가 서로 바뀌어야 합니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: ecde487e-96e5-85c2-ff87-227994f705ad
* Version Independent ID: f77588b3-9b31-f8ce-fad5-bf937337eb8c
* Content: [stackalloc 연산자 - C# 참조](https://docs.microsoft.com/ko-kr/dotnet/csharp/language-reference/operators/stackalloc)
* Content Source: [docs/csharp/language-reference/operators/stackalloc.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/csharp/language-reference/operators/stackalloc.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @sopepos
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
피드백을 주셔서 감사합니다.  

당사의 엔지니어링 팀이 귀하의 제안 사항을 검토하고 수락했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/dotnet/csharp/language-reference/operators/stackalloc에 게시했습니다.   

당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다.  

감사합니다. 
Microsoft DOCS 국제 팀
