### ISSUE TITLE
SSL 종료 및 Azure Application Gateway 부하 오프로딩 효과에 대한 해석의 애매함

### ISSUE THREAD

**Issue by zer0big** [dotnet/docs.ko-kr#231]
아래 원문상의 "improves the load" 에 대한 해석은 긍정적인 뉘앙스로 해석되는 것이 타당해 보입니다. 따라서 "증가"보다는 "개선"으로 해석되는 것이 타당해 보입니다. 검토 부탁 드립니다.
&lt;원문&gt;
This improves the load of your hosts by offloading CPU-intensive SSL termination and other routing duties to the Azure Application Gateway.
&lt;번역문&gt;
이는 CPU 집중적 SSL 종료 및 Azure Application Gateway로의 라우팅 듀티를 오프로딩하여 호스트의 로드를 증가시킵니다.
&lt;제안문&gt;
이는 CPU 집중적 SSL 종료 및 Azure Application Gateway로의 라우팅 듀티를 오프로딩하여 호스트의 로드를 개선시킵니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: b5a3c5f2-59c1-d0f1-15f5-446f81d36d2b
* Version Independent ID: b409992c-312e-639d-182b-2067e3561273
* Content: [API 게이트웨이 패턴과 클라이언트-마이크로 서비스 간 직접 통신](https://docs.microsoft.com/ko-kr/dotnet/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-api-gateway-pattern)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
안녕하세요, @zer0big님.   

피드백을 주셔서 감사합니다.  

당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/dotnet/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-api-gateway-pattern에 게시했습니다.   

당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다.  

감사합니다.  
Microsoft DOCS 국제 팀
