### ISSUE TITLE
should be efficiently aggregated에 대한 해석의 부자연스러움

### ISSUE THREAD

**Issue by zer0big** [dotnet/docs.ko-kr#232]
앞 문장에 언급한 문제점(시간 및 복잡성 증가)에 대한 조치(Aggregation)의 뉘앙스로 해석되어야 전체 문장이 자연스러을 것 같습니다.
따라서 다음과 같이 should를 "되어야 한다"라는 의미로 번역되도록 제안 드립니다. 검토 부탁 드립니다.

&lt;원문&gt;
Ideally, responses should be efficiently aggregated in the server side. This ...

&lt;번역문&gt;
이상적으로 응답은 서버 쪽에서 효율적으로 집계됩니다. 이렇게 하면 ...

&lt;제안문&gt;
이상적으로 응답은 서버 쪽에서 효율적으로 집계되어야 합니다. 이렇게 하면 ...

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: b5a3c5f2-59c1-d0f1-15f5-446f81d36d2b
* Version Independent ID: b409992c-312e-639d-182b-2067e3561273
* Content: [API 게이트웨이 패턴과 클라이언트-마이크로 서비스 간 직접 통신](https://docs.microsoft.com/ko-kr/dotnet/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-api-gateway-pattern)
* Content Source: [docs/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @zer0big
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
안녕하세요, @zer0big님.   

피드백을 주셔서 감사합니다.  

당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/dotnet/architecture/microservices/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-api-gateway-pattern에 게시했습니다.   

당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다.  

감사합니다.  
Microsoft DOCS 국제 팀
