### ISSUE TITLE
가격 예측(회귀) 예제서 만든 model을 재사용관련

### ISSUE THREAD

**Issue by jangsungLee** [dotnet/docs.ko-kr#233]
안녕하세요. C#으로 머신러닝을 만들려고 라이브러리를 찾다가 Microsofot.ML이라는 라이브러리를 알게 되었습니다.
주신 예제를 직접 실행해보았는데, 문제는 "Model.zip"처럼 모델을 파일로 만든후에 재생성 및 로드, 모델 다시 학습을 시키고 싶은데 방법을 알고 싶습니다.

Hi. I was looking for a library to make machine learning with C#, and I found Microsoft.ML
I ran the example you gave me, and the problem is that I want to make a file of the model, like "Model.zip," and then recreate, load, and relearn the model.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [자습서: 회귀를 사용하여 가격 예측 - ML.NET](https://docs.microsoft.com/ko-kr/dotnet/machine-learning/tutorials/predict-prices#feedback)
* Content Source: [docs/machine-learning/tutorials/predict-prices.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/machine-learning/tutorials/predict-prices.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by srvbpigh** [comment]
Hello, @jangsungLee
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
안녕하세요, @jangsungLee님.  

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다.  

따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/dotnet/docs/issues/17402에서 문제 상태를 확인하세요.  

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.   

감사합니다.  
Microsoft DOCS 국제 팀
