### ISSUE TITLE
Great page

### ISSUE THREAD

**Issue by es373** [dotnet/docs.ko-kr#234]
Great explanations for F#.
Though, I wish more examples showing its result directly via printfn function.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 89bef555-3de1-5d81-c02b-2ac8c049423b
* Version Independent ID: eb13ad9e-2c95-979b-6d6e-13d29653c6ba
* Content: [F# 둘러보기](https://docs.microsoft.com/ko-kr/dotnet/fsharp/tour#feedback)
* Content Source: [docs/fsharp/tour.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/fsharp/tour.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by srvbpigh** [comment]
Hello, @es373
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @es373 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
