### ISSUE TITLE
SOAP를 비누라고 번역함

### ISSUE THREAD

**Issue by seungyongshim** [dotnet/docs.ko-kr#241]
[여기에 피드백 입력]
SOAP를 비누라고 번역함

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 636134a9-c7f0-cd8e-9ea7-908bfcef1cab
* Version Independent ID: ac71cc00-972f-db7d-97f6-28555556a7ed
* Content: [소개 - WCF 개발자를 위한 gRPC](https://docs.microsoft.com/ko-kr/dotnet/architecture/grpc-for-wcf-developers/introduction)
* Content Source: [docs/architecture/grpc-for-wcf-developers/introduction.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/architecture/grpc-for-wcf-developers/introduction.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by srvbpigh** [comment]
Hello, @seungyongshim
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요 @seungyongshim  님,

기여해 주셔서 감사합니다.

기계 번역된 콘텐츠의 번역 문제와 관련하여 기여해 주신 부분이 현재 수락되어 있지 않습니다.

Microsoft는 사람이 번역한 콘텐츠와 관련하여 보내 주시는 피드백과 제안을 소중히 여깁니다. 사람이 번역한 콘텐츠는 기계 번역 엔진을 학습시키는 데 사용되므로 기여해 주신 부분은 시간이 지나면서 사람 번역과 기계 번역 모두의 품질을 향상합니다.

각 콘텐츠 파일의 헤더에 있는 ms.translationtype 메타데이터 값 “HT”(기계 번역의 경우 “MT”)로 사람이 번역한 항목을 기계 번역된 항목과 구별할 수 있습니다.

도움 주셔서 감사합니다.

Microsoft DOCS Global Experience Team 드림
