### ISSUE TITLE
Issue for translation

### ISSUE THREAD

**Issue by stjeong** [dotnet/docs.ko-kr#58]
pcbMethodSize
[out] 크기의 메서드를 지정 하는 정수입니다. 

==&gt;
pcbMethodSize
[out] 메서드의  크기를 지정하는 정수입니다. 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 41536a39-77d0-fa37-d7ea-9012eae8161d
* Version Independent ID: d4f73a35-6526-d04f-134c-f49625e27a53
* Content: [ICorProfilerInfo::GetILFunctionBody 메서드](https://docs.microsoft.com/ko-kr/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo-getilfunctionbody-method)
* Content Source: [docs/framework/unmanaged-api/profiling/icorprofilerinfo-getilfunctionbody-method.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/framework/unmanaged-api/profiling/icorprofilerinfo-getilfunctionbody-method.md)
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by LisandroSu** [comment]
안녕하세요. , @stjeong , 

피드백을 주셔서 감사합니다. 

사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 

감사합니다. 
Microsoft DOCS 국제 팀

**Comment by LisandroSu** [comment]
안녕하세요. , @stjeong ,

피드백을 주셔서 감사합니다.

사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다.

감사합니다.
Microsoft DOCS 국제 팀

**Comment by LisandroSu** [comment]
안녕하세요, @stjeong 님.  

 피드백을 주셔서 감사합니다. 

 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 [ICorProfilerInfo::GetILFunctionBody 메서드](https://docs.microsoft.com/ko-kr/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo-getilfunctionbody-method)에 게시했습니다.  

 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 

 감사합니다. 
Microsoft DOCS 국제 팀
