### ISSUE TITLE
용어의 표기 형식 통일

### ISSUE THREAD

**Issue by seokju-na** [dotnet/docs.ko-kr#70]
<img width="780" alt="screenshot" src="https://user-images.githubusercontent.com/13250888/46061929-276bb400-c1a3-11e8-93f6-2b2f511d28f9.png">

스크린샷에 보이는 것처럼 빨간색 부분에 적힌 용어를 **ViewModel**로 통일하는 것이 좋을 것 같습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 95f3dcd7-3220-e9cf-3ca6-90b1282410ec
* Version Independent ID: 6d2913e7-0111-5404-edd6-1a646066e5ce
* Content: [DDD 중심 마이크로 서비스 설계](https://docs.microsoft.com/ko-kr/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/ddd-oriented-microservice#designing-validations-in-the-domain-model-layer)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/ddd-oriented-microservice.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/ddd-oriented-microservice.md)
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
안녕하세요. , @seokju-na 

피드백을 주셔서 감사합니다. 

사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 

감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요, @seokju-na님.

 피드백을 주셔서 감사합니다.  

 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/ddd-oriented-microservice#designing-validations-in-the-domain-model-layer에 게시했습니다.   

 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다.  

 감사합니다.  

Microsoft DOCS 국제 팀
