### ISSUE TITLE
translation of docs/core/about.md

### ISSUE THREAD

**Issue by palindrom615** [dotnet/docs.ko-kr#71]
Hi!

I found [About .NET Core](https://docs.microsoft.com/ko-kr/dotnet/core/about) page has not been translated And I want to contribute.

I'm sure I've already read [contribution guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md) properly :wink: 

I've read commits of this repo and it seems like this repo is automatically managed by bot. Hopefully I'll trying to follow conventions and structure but I'm wonder is there anything to know for contribution.

I'm going to start it right now.

안녕하세요!

[.net 코어 정보](https://docs.microsoft.com/ko-kr/dotnet/core/about)가 번역이 아직 안된걸 발견해서 번역을 맡아서 하고 싶습니다.

[컨트리뷰션 가이드](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md)는 이미 읽었구요:wink: , 커밋 메시지도 읽었는데 자동으로 관리되는것 같던데 혹시 제가 컨트리뷰션할 때 알아야 될 게 있을 까요?

지금 바로 시작하려고 합니다.

**Comment by LisandroSu** [comment]
Hi @palindrom615 

Thank you for your feedback.

We will escalate this internally to see if we can include the page in the localization scope. In the meantime, feel free to create Pull Requests for any files that are already localized that you want to provide feedback for.

CC: @nokura 

Kind regards,
Microsoft DOCS International Team
