### ISSUE TITLE
markdown error 

### ISSUE THREAD

**Issue by angie4u** [dotnet/docs.ko-kr#99]
There are some markdown expression issue, so some images and sentences don't look right. 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 7c48990a-4edb-3e02-f7b7-36edb3eb91c5
* Version Independent ID: b93d07bb-44aa-04ef-4b60-0913cb9b1d2f
* Content: [추상 및 봉인 클래스와 클래스 멤버 - C# 프로그래밍 가이드](https://docs.microsoft.com/ko-kr/dotnet/csharp/programming-guide/classes-and-structs/abstract-and-sealed-classes-and-class-members#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/abstract-and-sealed-classes-and-class-members.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/csharp/programming-guide/classes-and-structs/abstract-and-sealed-classes-and-class-members.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @angie4u 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @angie4u

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ko-kr/dotnet/csharp/programming-guide/classes-and-structs/abstract-and-sealed-classes-and-class-members#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
